# lang.py

STRINGS = {
    "pt-br": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análise profissional para Football Manager",
        "tab_cadastro": "📝 Cadastrar Partida",
        "tab_dashboard": "📊 Dashboard",
        "tab_historico": "📋 Histórico",
        "tab_ia": "🧠 Assistente IA",
        "lbl_seu_time": "Seu time",
        "lbl_adversario": "Time adversário",
        "lbl_local": "Local do jogo",
        "lbl_resultado": "Resultado",
        "btn_salvar": "💾 Salvar partida",
        "msg_sucesso": "✅ Partida salva com sucesso!",
        "ia_analisar": "🪄 Gerar Relatório de Performance",
        "ia_veredito": "📋 Veredito do Assistente",
        "metrica_aproveitamento": "Aproveitamento",
        "total_partidas": "Total de Partidas",
        "vitorias": "Vitórias",
        "empates": "Empates",
        "derrotas": "Derrotas",
        "lbl_filtro_temporada": "Temporada",
        "lbl_filtro_competicao": "Competição",
        "analise_desempenho": "Análise de Desempenho",
        "gols_vs_xg": "Gols vs xG ao longo do tempo"
    },
    "en": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Professional Analysis for Football Manager",
        "tab_cadastro": "📝 Register Match",
        "tab_dashboard": "📊 Dashboard",
        "tab_historico": "📋 History",
        "tab_ia": "🧠 AI Assistant",
        "lbl_seu_time": "Your Team",
        "lbl_adversario": "Opponent",
        "lbl_local": "Venue",
        "lbl_resultado": "Result",
        "btn_salvar": "💾 Save Match",
        "msg_sucesso": "✅ Match saved successfully!",
        "ia_analisar": "🪄 Generate Performance Report",
        "ia_veredito": "📋 Assistant's Verdict",
        "metrica_aproveitamento": "Win Rate",
        "total_partidas": "Total Matches",
        "vitorias": "Wins",
        "empates": "Draws",
        "derrotas": "Losses",
        "lbl_filtro_temporada": "Season",
        "lbl_filtro_competicao": "Competition",
        "analise_desempenho": "Performance Analysis",
        "gols_vs_xg": "Goals vs xG Over Time"
    },
    "es": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análisis profesional para Football Manager",
        "tab_cadastro": "📝 Registrar Partido",
        "tab_dashboard": "📊 Panel",
        "tab_historico": "📋 Historial",
        "tab_ia": "🧠 Asistente IA",
        "lbl_seu_time": "Tu Equipo",
        "lbl_adversario": "Rival",
        "lbl_local": "Lugar",
        "lbl_resultado": "Resultado",
        "btn_salvar": "💾 Guardar Partido",
        "msg_sucesso": "✅ ¡Partido guardado con éxito!",
        "ia_analisar": "🪄 Generar Informe de Rendimiento",
        "ia_veredito": "📋 Veredicto del Asistente",
        "metrica_aproveitamento": "Rendimiento",
        "total_partidas": "Total de Partidos",
        "vitorias": "Victorias",
        "empates": "Empates",
        "derrotas": "Derrotas",
        "lbl_filtro_temporada": "Temporada",
        "lbl_filtro_competicao": "Competición",
        "analise_desempenho": "Análisis de Rendimiento",
        "gols_vs_xg": "Goles vs xG a lo largo del tiempo"
    },
    "pt-pt": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análise profissional para Football Manager",
        "tab_cadastro": "📝 Registar Partida",
        "tab_dashboard": "📊 Painel",
        "tab_historico": "📋 Histórico",
        "tab_ia": "🧠 Assistente IA",
        "lbl_seu_time": "A tua equipa",
        "lbl_adversario": "Adversário",
        "lbl_local": "Local do jogo",
        "lbl_resultado": "Resultado",
        "btn_salvar": "💾 Guardar partida",
        "msg_sucesso": "✅ Partida guardada com sucesso!",
        "ia_analisar": "🪄 Gerar Relatório de Performance",
        "ia_veredito": "📋 Veredito do Assistente",
        "metrica_aproveitamento": "Aproveitamento",
        "total_partidas": "Total de Partidas",
        "vitorias": "Vitórias",
        "empates": "Empates",
        "derrotas": "Derrotas",
        "lbl_filtro_temporada": "Temporada",
        "lbl_filtro_competicao": "Competição",
        "analise_desempenho": "Análise de Desempenho",
        "gols_vs_xg": "Golos vs xG ao longo do tempo"
    }
}