# lang.py

STRINGS = {
    "pt-br": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análise profissional para Football Manager",
        "tab_cadastro": "📝 Cadastrar Partida",
        "tab_dashboard": "📊 Dashboard",
        "tab_historico": "📋 Histórico",
        "tab_ia": "🧠 Assistente IA",
        "lbl_seu_time": "Seu time",
        "lbl_adversario": "Time adversário",
        "lbl_local": "Local do jogo",
        "lbl_resultado": "Resultado",
        "btn_salvar": "💾 Salvar partida",
        "msg_sucesso": "✅ Partida salva com sucesso!",
        "ia_analisar": "🪄 Gerar Relatório de Performance",
        "ia_veredito": "📋 Veredito do Assistente",
        "metrica_aproveitamento": "Aproveitamento",
    },
    "en": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Professional Analysis for Football Manager",
        "tab_cadastro": "📝 Register Match",
        "tab_dashboard": "📊 Dashboard",
        "tab_historico": "📋 History",
        "tab_ia": "🧠 AI Assistant",
        "lbl_seu_time": "Your Team",
        "lbl_adversario": "Opponent",
        "lbl_local": "Venue",
        "lbl_resultado": "Result",
        "btn_salvar": "💾 Save Match",
        "msg_sucesso": "✅ Match saved successfully!",
        "ia_analisar": "🪄 Generate Performance Report",
        "ia_veredito": "📋 Assistant's Verdict",
        "metrica_aproveitamento": "Win Rate",
    },
    "es": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análisis profesional para Football Manager",
        "tab_cadastro": "📝 Registrar Partido",
        "tab_dashboard": "📊 Panel",
        "tab_historico": "📋 Historial",
        "tab_ia": "🧠 Asistente IA",
        "lbl_seu_time": "Tu Equipo",
        "lbl_adversario": "Rival",
        "lbl_local": "Lugar",
        "lbl_resultado": "Resultado",
        "btn_salvar": "💾 Guardar Partido",
        "msg_sucesso": "✅ ¡Partido guardado con éxito!",
        "ia_analisar": "🪄 Generar Informe de Rendimiento",
        "ia_veredito": "📋 Veredicto del Asistente",
        "metrica_aproveitamento": "Rendimiento",
    },
    "pt-pt": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análise profissional para Football Manager",
        "tab_cadastro": "📝 Registar Partida",
        "tab_dashboard": "📊 Painel",
        "tab_historico": "📋 Histórico",
        "tab_ia": "🧠 Assistente IA",
        "lbl_seu_time": "A tua equipa",
        "lbl_adversario": "Adversário",
        "lbl_local": "Local do jogo",
        "lbl_resultado": "Resultado",
        "btn_salvar": "💾 Guardar partida",
        "msg_sucesso": "✅ Partida guardada com sucesso!",
        "ia_analisar": "🪄 Gerar Relatório de Performance",
        "ia_veredito": "📋 Veredito do Assistente",
        "metrica_aproveitamento": "Aproveitamento",
    }
}